# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: python:3.7.1

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      # Build and push docker image
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.3-ce"
            wget -O - https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz | tar xz -C /tmp
            mv /tmp/docker/* /usr/bin

      - run:
          name: PIP install
          command: pip install --user -r requirements.txt -r tests/requirements.txt

      - run:
          name: run tests
          command: |
            ./tests/bin/tests.sh

      - run:
          name: build docker image
          command: |
            docker build -t custom-curation-gear --target base .

      - deploy:
          name: Deploy Docker Image
          command: |
            if [ "$DOCKER_USER" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              if [ "$CIRCLE_TAG" ]; then
                docker tag custom-curation-gear flywheel/custom-curation-gear:${CIRCLE_TAG}
                docker push flywheel/custom-curation-gear:${CIRCLE_TAG}
                (
                  IFS='.' read -ra VER_PARTS <<< "${CIRCLE_TAG}"
                  if [ "3" -eq "${#VER_PARTS[@]}" ]; then
                    MINOR_TAG="${VER_PARTS[0]}.${VER_PARTS[1]}"
                    docker tag custom-curation-gear flywheel/custom-curation-gear:${MINOR_TAG}
                    docker push flywheel/custom-curation-gear:${MINOR_TAG}
                  fi
                )
              fi
              if [ "$CIRCLE_BRANCH" == "master" ]; then
                docker tag custom-curation-gear flywheel/custom-curation-gear:latest
                docker push flywheel/custom-curation-gear:latest
              fi
            fi

